spring.application.name=bookerang

# R2DBC Connection Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/bookerangdb
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}


