spring.application.name=bookerang

spring.datasource.url=jdbc:mysql://localhost:3306/bookerang_db
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.data.jdbc.dialect=mysql
